#include <stdio.h>
#include "includes/ft_printf.h"

int main()
{
	char c;
	char *str;
	char *str1;
	char *str2;
	char *str_null;
	char *str3;
	int	num;
	long long int i;
	int x;
	char a;
	unsigned long long int h;
	char	b;
	long long int	m;
	
	b = 'x';
	h = 18446744073709551615LLU ;
	a = 34;
	x = 1;
	i = 9223372036854775807;
	m = -9223372036854775807;
	num = 12345;
	c = 'A';
	str = "sTrInG 1";
	str1 = "StRiNg 2";
	str2 = "54321";
	str3 = "0123456789";
	str_null = NULL;

	printf("\nd_i minus ints\n");
	ft_printf("MY PRINTF:\nd_i int: |%lli|\n", m);
	printf("PRINTF:\nd_i int: |%lli|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%15lli|\n", m);
	printf("PRINTF:\nd_i int: |%15lli|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%+lld|\n", m);
	printf("PRINTF:\nd_i int: |%+lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |% lld|\n", m);
	printf("PRINTF:\nd_i int: |% lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%+15.6lld|\n", m);
	printf("PRINTF:\nd_i int: |%+15.6lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%-+15.24lld|\n", m);
	printf("PRINTF:\nd_i int: |%-+15.24lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%- 15.24lld|\n", m);
	printf("PRINTF:\nd_i int: |%- 15.24lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%-30lld|\n", m);
	printf("PRINTF:\nd_i int: |%-30lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%030lld|\n", m);
	printf("PRINTF:\nd_i int: |%030lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |% 030lld|\n", m);
	printf("PRINTF:\nd_i int: |% 030lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%030lld|\n", m);
	printf("PRINTF:\nd_i int: |%030lld|\n", m);
	ft_printf("MY PRINTF:\nd_i int: |%+1lld|\n", m);
	printf("PRINTF:\nd_i int: |%+1lld|\n", m);
	printf("\nd_i ints\n\n\n\n");

	ft_printf("MY PRINTF:\nd_i int: |%035.lld|\n", i);
	printf("PRINTF:\nd_i int: |%035.lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%035.lld|\n", i);
	printf("PRINTF:\nd_i int: |%035.lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%035.1lld|\n", i);
	printf("PRINTF:\nd_i int: |%035.1lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%-035.1lld|\n", i);
	printf("PRINTF:\nd_i int: |%-035.1lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%lli|\n", i);
	printf("PRINTF:\nd_i int: |%lli|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%15lli|\n", i);
	printf("PRINTF:\nd_i int: |%15lli|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%+lld|\n", i);
	printf("PRINTF:\nd_i int: |%+lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |% lld|\n", i);
	printf("PRINTF:\nd_i int: |% lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%+15.24lld|\n", i);
	printf("PRINTF:\nd_i int: |%+15.24lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%-+15.24lld|\n", i);
	printf("PRINTF:\nd_i int: |%-+15.24lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |% -15.24lld|\n", i);
	printf("PRINTF:\nd_i int: |% -15.24lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%30.10lld|\n", i);
	printf("PRINTF:\nd_i int: |%30.10lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%+030lld|\n", i);
	printf("PRINTF:\nd_i int: |%+030lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%030lld|\n", i);
	printf("PRINTF:\nd_i int: |%030lld|\n", i);
	ft_printf("MY PRINTF:\nd_i int: |%- lld|\n", i);
	printf("PRINTF:\nd_i int: |%- lld|\n", i);
	printf("\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%+010.2lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%+010.2lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%+010.1lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%+010.1lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%+0.1lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%+0.1lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%+10.1lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%+10.1lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%-+10.1lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%-+10.1lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%.lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%.lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%3.lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%3.lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%+3.lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%+3.lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%+03.lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%+03.lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |% .lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |% .lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%0.lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%0.lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%04.lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%04.lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%+.lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%+.lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%+030lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%+030lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |% -10lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |% -10lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%  10lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%  10lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%- 10lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%- 10lld|\n", 0LL);
	ft_printf("MY PRINTF:\nd_i int: |%-+10lld|\n", 0LL);
	printf("PRINTF:\nd_i int: |%-+10lld|\n", 0LL);
	printf("\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%+010.2lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%+010.2lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%+010.1lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%+010.1lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%+0.1lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%+0.1lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%+10.1lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%+10.1lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%-+10.1lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%-+10.1lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%.lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%3.lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%3.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%+3.lld|\n", 1LL); /***********/
	printf("PRINTF:\nd_i int: |%+3.lld|\n", 1LL);
	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |% 5.lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |% 5.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%05.lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%05.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.lld|\n", 1LL); //
	printf("PRINTF:\nd_i int: |%- 5.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |% 5.1lld|\n", 11LL); 
	printf("PRINTF:\nd_i int: |% 5.1lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%- 5lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%- 5lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%- .lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%- .lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |% 05.lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |% 05.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%-+5.1lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%-+5.1lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.1lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%- 5.1lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%0- 5.lld|\n", 1LL); //
	printf("PRINTF:\nd_i int: |%0- 5.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%-05.lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%-05.lld|\n", 1LL);

	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%+03.lld|\n", 1LL); /**********/
	printf("PRINTF:\nd_i int: |%+03.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |% .lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |% .lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%0.lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%0.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%04.lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%04.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%+.lld|\n", 1LL); 
	printf("PRINTF:\nd_i int: |%+.lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%+030lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%+030lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |% -10lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |% -10lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%  10lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%  10lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%- 10lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%- 10lld|\n", 1LL);
	ft_printf("MY PRINTF:\nd_i int: |%-+10lld|\n", 1LL);
	printf("PRINTF:\nd_i int: |%-+10lld|\n", 1LL);
	printf("\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%+010.2lld|\n", 11LL); 
	printf("PRINTF:\nd_i int: |%+010.2lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%+010.1lld|\n", 11LL); /***********/
	printf("PRINTF:\nd_i int: |%+010.1lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%+0.1lld|\n", 11LL); 
	printf("PRINTF:\nd_i int: |%+0.1lld|\n", 11LL); /**/
	ft_printf("MY PRINTF:\nd_i int: |%+0.1lld|\n", 11LL); 
	printf("PRINTF:\nd_i int: |%+0.1lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%+10.1lld|\n", 11LL); /*************/
	printf("PRINTF:\nd_i int: |%+10.1lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%-+10.1lld|\n", 11LL); /**************/
	printf("PRINTF:\nd_i int: |%-+10.1lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%.lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%.lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%3.lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%3.lld|\n", 11LL);
	printf("\n\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%+3.lld|\n", 11LL); /**************/
	printf("PRINTF:\nd_i int: |%+3.lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%+03.lld|\n", 11LL); /**************/
	printf("PRINTF:\nd_i int: |%+03.lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |% .lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |% .lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%0.lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%0.lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%04.lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%04.lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%+.lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%+.lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%+030lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%+030lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |% -10lld|\n", 11LL); 
	printf("PRINTF:\nd_i int: |% -10lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%  10lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%  10lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%- 10lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%- 10lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%-+10lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%-+10lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%020.4lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%020.4lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%010.lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%010.lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%010.1lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%010.1lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%010.2lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%010.2lld|\n", 11LL);
	ft_printf("MY PRINTF:\nd_i int: |%010.4lld|\n", 11LL);
	printf("PRINTF:\nd_i int: |%010.4lld|\n", 11LL);
	printf("\n\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%+010.2d|\n", 0);
	printf("PRINTF:\nd_i int: |%+010.2d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%+010.1d|\n", 0);
	printf("PRINTF:\nd_i int: |%+010.1d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%+0.1d|\n", 0);
	printf("PRINTF:\nd_i int: |%+0.1d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%+10.1d|\n", 0);
	printf("PRINTF:\nd_i int: |%+10.1d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%-+10.1d|\n", 0);
	printf("PRINTF:\nd_i int: |%-+10.1d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%.d|\n", 0);
	printf("PRINTF:\nd_i int: |%.d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%3.d|\n", 0);
	printf("PRINTF:\nd_i int: |%3.d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%+3.d|\n", 0);
	printf("PRINTF:\nd_i int: |%+3.d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%+03.d|\n", 0);
	printf("PRINTF:\nd_i int: |%+03.d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |% .d|\n", 0);
	printf("PRINTF:\nd_i int: |% .d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%0.d|\n", 0);
	printf("PRINTF:\nd_i int: |%0.d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%04.d|\n", 0);
	printf("PRINTF:\nd_i int: |%04.d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%+.d|\n", 0);
	printf("PRINTF:\nd_i int: |%+.d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%+030d|\n", 0);
	printf("PRINTF:\nd_i int: |%+030d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |% -10d|\n", 0);
	printf("PRINTF:\nd_i int: |% -10d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%  10d|\n", 0);
	printf("PRINTF:\nd_i int: |%  10d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%- 10d|\n", 0);
	printf("PRINTF:\nd_i int: |%- 10d|\n", 0);
	ft_printf("MY PRINTF:\nd_i int: |%-+10d|\n", 0);
	printf("PRINTF:\nd_i int: |%-+10d|\n", 0);
	printf("\n\nUnsigned Ints:\n");

	printf("PRINTF:\nu int: |%10.u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.u|\n", 0);
	printf("PRINTF:\nu int: |%-10.u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.u|\n", 0);
	printf("PRINTF:\nu int: |%010.u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010.u|\n", 0);
	printf("PRINTF:\nu int: |%.u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%.u|\n", 0);
	printf("PRINTF:\nu int: |%-10.15u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.15u|\n", 0);
	printf("PRINTF:\nu int: |%-10u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10u|\n", 0);
	printf("PRINTF:\nu int: |%-10.1u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.1u|\n", 0);
	printf("PRINTF:\nu int: |%-5u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-5u|\n", 0);
	printf("PRINTF:\nu int: |%10u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10u|\n", 0);
	printf("PRINTF:\nu int: |%10.15u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.15u|\n", 0);
	printf("PRINTF:\nu int: |%10.u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.u|\n", 0);
	printf("PRINTF:\nu int: |%10.1u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.1u|\n", 0);
	printf("PRINTF:\nu int: |%5u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%5u|\n", 0);
	printf("PRINTF:\nu int: |%010u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010u|\n", 0);
	printf("PRINTF:\nu int: |%010.20u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010.20u|\n", 0);
	printf("PRINTF:\nu int: |%0u|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%0u|\n", 0);
	printf("PRINTF:\nu int: |%10llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llu|\n", h);
	printf("PRINTF:\nu int: |%010llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%010llu|\n", h);
	printf("PRINTF:\nu int: |%-10llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10llu|\n", h);
	printf("PRINTF:\nu int: |%-10.15llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.15llu|\n", h);
	printf("PRINTF:\nu int: |%-10.llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.llu|\n", h);
	printf("PRINTF:\nu int: |%-10.1llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.1llu|\n", h);
	printf("PRINTF:\nu int: |%10.1llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.1llu|\n", h);
	printf("PRINTF:\nu int: |%-10.30llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.30llu|\n", h);
	printf("PRINTF:\nu int: |%10.30llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.30llu|\n", h);
	printf("PRINTF:\nu int: |%-5llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-5llu|\n", h);
	printf("PRINTF:\nu int: |%10llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llu|\n", h);
	printf("PRINTF:\nu int: |%10.15llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.15llu|\n", h);
	printf("PRINTF:\nu int: |%10.llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.llu|\n", h);
	printf("PRINTF:\nu int: |%10.1llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.1llu|\n", h);
	printf("PRINTF:\nu int: |%5llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%5llu|\n", h);
	printf("PRINTF:\nu int: |%030llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llu|\n", h);
	printf("PRINTF:\nu int: |%010.20llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.20llu|\n", h);
	printf("PRINTF:\nu int: |%0llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%0llu|\n", h);
	printf("PRINTF:\nu int: |%10llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llu|\n", h);
	printf("PRINTF:\nu int: |%030llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llu|\n", h);
	printf("PRINTF:\nu int: |%030llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llu|\n", h);
	printf("PRINTF:\nu int: |%.llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%.llu|\n", h);
	printf("PRINTF:\nu int: |%.30llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%.30llu|\n", h);
	printf("PRINTF:\nu int: |%-.30llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-.30llu|\n", h);
	printf("PRINTF:\nu int: |%050llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%050llu|\n", h);
	printf("PRINTF:\nu int: |%llu|\n", h);
	ft_printf("MY PRINTF:\nu int: |%llu|\n", h);
	printf("\nUnsigned Big Hexs\n");
	printf("PRINTF:\nu int: |%10.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.X|\n", 0);
	printf("PRINTF:\nu int: |%-10.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.X|\n", 0);
	printf("PRINTF:\nu int: |%010.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010.X|\n", 0);
	printf("PRINTF:\nu int: |%.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%.X|\n", 0);
	printf("PRINTF:\nu int: |%-10.15X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.15X|\n", 0);
	printf("PRINTF:\nu int: |%-10X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10X|\n", 0);
	printf("PRINTF:\nu int: |%-10.1X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.1X|\n", 0);
	printf("PRINTF:\nu int: |%-5X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-5X|\n", 0);
	printf("PRINTF:\nu int: |%10X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10X|\n", 0);
	printf("PRINTF:\nu int: |%10.15X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.15X|\n", 0);
	printf("PRINTF:\nu int: |%10.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.X|\n", 0);
	printf("PRINTF:\nu int: |%10.1X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.1X|\n", 0);
	printf("PRINTF:\nu int: |%5X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%5X|\n", 0);
	printf("PRINTF:\nu int: |%010X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010X|\n", 0);
	printf("PRINTF:\nu int: |%010.20X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010.20X|\n", 0);
	printf("PRINTF:\nu int: |%0X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%0X|\n", 0);


	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%# 5.llx|\n", 0ull);
	printf("PRINTF:\nd_i int: |%# 5.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#05.llx|\n", 0ull);
	printf("PRINTF:\nd_i int: |%#05.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.llx|\n", 0ull); //
	printf("PRINTF:\nd_i int: |%#- 5.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 5.1lld|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%# 5.1lld|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%#- 5llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- .llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%#- .llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 05.llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%# 05.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-+5.1llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%#-+5.1llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.1llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%#- 5.1llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#0- 5.llx|\n", 0ull); //
	printf("PRINTF:\nd_i int: |%#0- 5.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-05.llx|\n", 0ull);
	printf("PRINTF:\nd_i int: |%#-05.llx|\n", 0ull);
	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%# 5.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%# 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.llx|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%#- 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 5.1llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%# 5.1llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- 5llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- .llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- .llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 05.llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%# 05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-+5.1llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#-+5.1llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.1llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- 5.1llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#0- 5.llx|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%#0- 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#-05.llx|\n", 1ull);

	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |% 5.llx|\n", 0ull);
	printf("PRINTF:\nd_i int: |% 5.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%05.llx|\n", 0ull);
	printf("PRINTF:\nd_i int: |%05.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.llx|\n", 0ull); //
	printf("PRINTF:\nd_i int: |%- 5.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |% 5.1lld|\n", 0ull); 
	printf("PRINTF:\nd_i int: |% 5.1lld|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%- 5llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%- .llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%- .llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |% 05.llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |% 05.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%-+5.1llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%-+5.1llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.1llx|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%- 5.1llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%0- 5.llx|\n", 0ull); //
	printf("PRINTF:\nd_i int: |%0- 5.llx|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%-05.llx|\n", 0ull);
	printf("PRINTF:\nd_i int: |%-05.llx|\n", 0ull);
	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |% 5.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |% 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.llx|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%- 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |% 5.1lld|\n", 1ull); 
	printf("PRINTF:\nd_i int: |% 5.1lld|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%- 5llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%- .llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%- .llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |% 05.llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |% 05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%-+5.1llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%-+5.1llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.1llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%- 5.1llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%0- 5.llx|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%0- 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%-05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%-05.llx|\n", 1ull);

	
		printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |% 5.llo|\n", 0ull);
	printf("PRINTF:\nd_i int: |% 5.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%05.llo|\n", 0ull);
	printf("PRINTF:\nd_i int: |%05.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.llo|\n", 0ull); //
	printf("PRINTF:\nd_i int: |%- 5.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |% 5.1lld|\n", 0ull); 
	printf("PRINTF:\nd_i int: |% 5.1lld|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%- 5llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%- .llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%- .llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |% 05.llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |% 05.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%-+5.1llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%-+5.1llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.1llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%- 5.1llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%0- 5.llo|\n", 0ull); //
	printf("PRINTF:\nd_i int: |%0- 5.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%-05.llo|\n", 0ull);
	printf("PRINTF:\nd_i int: |%-05.llo|\n", 0ull);
	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |% 5.llo|\n", 1ull);
	printf("PRINTF:\nd_i int: |% 5.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%05.llo|\n", 1ull);
	printf("PRINTF:\nd_i int: |%05.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.llo|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%- 5.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |% 5.1lld|\n", 1ull); 
	printf("PRINTF:\nd_i int: |% 5.1lld|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%- 5llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%- .llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%- .llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |% 05.llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |% 05.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%-+5.1llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%-+5.1llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%- 5.1llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%- 5.1llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%0- 5.llo|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%0- 5.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%-05.llo|\n", 1ull);
	printf("PRINTF:\nd_i int: |%-05.llo|\n", 1ull);
	
	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%# 5.llo|\n", 0ull);
	printf("PRINTF:\nd_i int: |%# 5.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#05.llo|\n", 0ull);
	printf("PRINTF:\nd_i int: |%#05.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.llo|\n", 0ull); //
	printf("PRINTF:\nd_i int: |%#- 5.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 5.1lld|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%# 5.1lld|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%#- 5llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- .llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%#- .llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 05.llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%# 05.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-+5.1llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%#-+5.1llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.1llo|\n", 0ull); 
	printf("PRINTF:\nd_i int: |%#- 5.1llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#0- 5.llo|\n", 0ull); //
	printf("PRINTF:\nd_i int: |%#0- 5.llo|\n", 0ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-05.llo|\n", 0ull);
	printf("PRINTF:\nd_i int: |%#-05.llo|\n", 0ull);
	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%# 5.llo|\n", 1ull);
	printf("PRINTF:\nd_i int: |%# 5.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#05.llo|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#05.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.llo|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%#- 5.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 5.1lld|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%# 5.1lld|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- 5llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- .llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- .llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 05.llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%# 05.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-+5.1llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#-+5.1llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.1llo|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- 5.1llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#0- 5.llo|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%#0- 5.llo|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-05.llo|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#-05.llo|\n", 1ull);

	printf("\n\n\n\n\n\n\n");
	ft_printf("MY PRINTF:\nd_i int: |%# 5.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%# 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.llx|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%#- 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 5.1llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%# 5.1llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- 5llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- .llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- .llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 05.llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%# 05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-+5.1llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#-+5.1llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#- 5.1llx|\n", 1ull); 
	printf("PRINTF:\nd_i int: |%#- 5.1llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#0- 5.llx|\n", 1ull); //
	printf("PRINTF:\nd_i int: |%#0- 5.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#-05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-01.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#-01.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-1.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#-1.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%# -05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%# -05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#-05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#-05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%#05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%#05.llx|\n", 1ull);
	ft_printf("MY PRINTF:\nd_i int: |%# 05.llx|\n", 1ull);
	printf("PRINTF:\nd_i int: |%# 05.llx|\n", 1ull);


	system("leaks a.out");
	return 0;
}