#include <stdio.h>
#include "includes/ft_printf.h"

int main()
{
	char c;
	char *str;
	char *str1;
	char *str2;
	char *str_null;
	char *str3;
	int	num;
	long long int i;
	int x;
	char a;
	unsigned long long int h;
	char	b;
	long long int	m;
	int re;
	int my;
	
	my = 0;
	re = 0;
	b = 'x';
	h = 1LLU ;
	a = 34;
	x = 1;
	i = 9223372036854775807;
	m = -9223372036854775807;
	num = 12345;
	c = 'A';
	str = "sTrInG 1";
	str1 = "StRiNg 2";
	str2 = "54321";
	str3 = "0123456789";
	str_null = NULL;

	printf("\nHex's\n");
	printf("PRINTF:\nu int: |%10llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llX|\n", h);
	printf("PRINTF:\nu int: |%010llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%010llX|\n", h);
	printf("PRINTF:\nu int: |%-10llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10llX|\n", h);
	printf("PRINTF:\nu int: |%-10.15llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.15llX|\n", h);
	printf("PRINTF:\nu int: |%-10.llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.llX|\n", h);
	printf("PRINTF:\nu int: |%-10.1llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.1llX|\n", h);
	printf("PRINTF:\nu int: |%10.1llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.1llX|\n", h);
	printf("PRINTF:\nu int: |%-10.30llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.30llX|\n", h);
	printf("PRINTF:\nu int: |%10.30llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.30llX|\n", h);
	printf("PRINTF:\nu int: |%-5llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-5llX|\n", h);
	printf("PRINTF:\nu int: |%10llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llX|\n", h);
	printf("PRINTF:\nu int: |%10.15llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.15llX|\n", h);
	printf("PRINTF:\nu int: |%10.llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.llX|\n", h);
	printf("PRINTF:\nu int: |%10.1llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.1llX|\n", h);
	printf("PRINTF:\nu int: |%5llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%5llX|\n", h);
	printf("PRINTF:\nu int: |%030llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llX|\n", h);
	printf("PRINTF:\nu int: |%010.20llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.20llX|\n", h);
	printf("PRINTF:\nu int: |%0llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%0llX|\n", h);
	printf("PRINTF:\nu int: |%10llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llX|\n", h);
	printf("PRINTF:\nu int: |%030llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llX|\n", h);
	printf("PRINTF:\nu int: |%030llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llX|\n", h);
	printf("PRINTF:\nu int: |%.llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%.llX|\n", h);
	printf("PRINTF:\nu int: |%.30llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%.30llX|\n", h);
	printf("PRINTF:\nu int: |%-.30llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-.30llX|\n", h);
	printf("PRINTF:\nu int: |%050llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%050llX|\n", h); //
	printf("PRINTF:\nu int: |%llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%llX|\n", h);

	printf("\nUnsigned Small Hexs\n");
	printf("PRINTF:\nu int: |%10.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.x|\n", 0);
	printf("PRINTF:\nu int: |%-10.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.x|\n", 0);
	printf("PRINTF:\nu int: |%010.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010.x|\n", 0);
	printf("PRINTF:\nu int: |%.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%.x|\n", 0);
	printf("PRINTF:\nu int: |%-10.15x|---\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.15x|\n", 0);
	printf("PRINTF:\nu int: |%-10x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10x|\n", 0);
	printf("PRINTF:\nu int: |%-10.1x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-10.1x|\n", 0);
	printf("PRINTF:\nu int: |%-5x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%-5x|\n", 0);
	printf("PRINTF:\nu int: |%10x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10x|\n", 0);
	printf("PRINTF:\nu int: |%10.15x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.15x|---\n", 0);
	printf("PRINTF:\nu int: |%10.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.x|\n", 0);
	printf("PRINTF:\nu int: |%10.1x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%10.1x|\n", 0);
	printf("PRINTF:\nu int: |%5x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%5x|\n", 0);
	printf("PRINTF:\nu int: |%010x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010x|\n", 0);
	printf("PRINTF:\nu int: |%010.20x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%010.20x|\n", 0);
	printf("PRINTF:\nu int: |%0x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%0x|\n", 0);
	printf("PRINTF:\nu int: |%10llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llx|\n", h);
	printf("PRINTF:\nu int: |%010llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%010llx|\n", h);
	printf("PRINTF:\nu int: |%-10llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10llx|\n", h);
	printf("PRINTF:\nu int: |%-10.15llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.15llx|\n", h);
	printf("PRINTF:\nu int: |%-10.llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.llx|\n", h);
	printf("PRINTF:\nu int: |%-10.1llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.1llx|\n", h);
	printf("PRINTF:\nu int: |%10.1llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.1llx|\n", h);
	printf("PRINTF:\nu int: |%-10.30llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.30llx|\n", h);
	printf("PRINTF:\nu int: |%10.30llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.30llx|\n", h);
	printf("PRINTF:\nu int: |%-5llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-5llx|\n", h);
	printf("PRINTF:\nu int: |%10llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llx|\n", h);
	printf("PRINTF:\nu int: |%10.15llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.15llx|\n", h);
	printf("PRINTF:\nu int: |%10.llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.llx|\n", h);
	printf("PRINTF:\nu int: |%10.1llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.1llx|\n", h);
	printf("PRINTF:\nu int: |%5llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%5llx|\n", h);
	printf("PRINTF:\nu int: |%030llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llx|\n", h);
	printf("PRINTF:\nu int: |%010.20llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.20llx|\n", h);
	printf("PRINTF:\nu int: |%0llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%0llx|\n", h);
	printf("PRINTF:\nu int: |%10llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llx|\n", h);
	printf("PRINTF:\nu int: |%030llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llx|\n", h);
	printf("PRINTF:\nu int: |%030llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llx|\n", h);
	printf("PRINTF:\nu int: |%.llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%.llx|\n", h);
	printf("PRINTF:\nu int: |%.30llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%.30llx|\n", h);
	printf("PRINTF:\nu int: |%-.30llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-.30llx|\n", h);
	printf("PRINTF:\nu int: |%050llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%050llx|\n", h);
	printf("PRINTF:\nu int: |%llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%llx|\n", h);
	printf("\nUnsigned Octals:\n");
	printf("PRINTF:\nu int: |%10.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%10.o|\n", 1);
	printf("PRINTF:\nu int: |%-10.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%-10.o|\n", 1);
	printf("PRINTF:\nu int: |%010.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%010.o|\n", 1);
	printf("PRINTF:\nu int: |%.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%.o|\n", 1);
	printf("PRINTF:\nu int: |%-10.15o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%-10.15o|\n", 1);
	printf("PRINTF:\nu int: |%-10o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%-10o|\n", 1);
	printf("PRINTF:\nu int: |%-10.1o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%-10.1o|\n", 1);
	printf("PRINTF:\nu int: |%-5o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%-5o|\n", 1);
	printf("PRINTF:\nu int: |%10o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%10o|\n", 1);
	printf("PRINTF:\nu int: |%10.15o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%10.15o|\n", 1);
	printf("PRINTF:\nu int: |%10.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%10.o|\n", 1);
	printf("PRINTF:\nu int: |%10.1o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%10.1o|\n", 1);
	printf("PRINTF:\nu int: |%5o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%5o|\n", 1);
	printf("PRINTF:\nu int: |%010o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%010o|\n", 1);
	printf("PRINTF:\nu int: |%010.20o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%010.20o|\n", 1); 
	printf("PRINTF:\nu int: |%0o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%0o|\n", 1);
	printf("PRINTF:\nu int: |%10llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llo|\n", h);
	printf("PRINTF:\nu int: |%010llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%010llo|\n", h);
	printf("PRINTF:\nu int: |%-10llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10llo|\n", h);
	printf("PRINTF:\nu int: |%-10.15llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.15llo|\n", h);
	printf("PRINTF:\nu int: |%-10.llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.llo|\n", h);
	printf("PRINTF:\nu int: |%-10.1llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.1llo|\n", h);
	printf("PRINTF:\nu int: |%10.1llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.1llo|\n", h);
	printf("PRINTF:\nu int: |%-10.30llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-10.30llo|\n", h);
	printf("PRINTF:\nu int: |%10.30llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.30llo|\n", h);
	printf("PRINTF:\nu int: |%-5llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-5llo|\n", h);
	printf("PRINTF:\nu int: |%10llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llo|\n", h);
	printf("PRINTF:\nu int: |%10.15llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.15llo|\n", h);
	printf("PRINTF:\nu int: |%10.llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.llo|\n", h);
	printf("PRINTF:\nu int: |%10.1llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.1llo|\n", h);
	printf("PRINTF:\nu int: |%5llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%5llo|\n", h);
	printf("PRINTF:\nu int: |%030llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llo|\n", h);
	printf("PRINTF:\nu int: |%010.20llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10.20llo|\n", h);
	printf("PRINTF:\nu int: |%0llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%0llo|\n", h);
	printf("PRINTF:\nu int: |%10llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%10llo|\n", h);
	printf("PRINTF:\nu int: |%030llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llo|\n", h);
	printf("PRINTF:\nu int: |%030llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%030llo|\n", h);
	printf("PRINTF:\nu int: |%.llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%.llo|\n", h);
	printf("PRINTF:\nu int: |%.30llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%.30llo|\n", h);
	printf("PRINTF:\nu int: |%-.30llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%-.30llo|\n", h);
	printf("PRINTF:\nu int: |%050llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%050llo|\n", h);
	printf("PRINTF:\nu int: |%llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%llo|\n", h);

	
	printf("\nUnsigned Big Hexs\n");
	printf("PRINTF:\nu int: |%#10.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.X|\n", 0);
	printf("PRINTF:\nu int: |%#-10.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.X|\n", 0);
	printf("PRINTF:\nu int: |%#010.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010.X|\n", 0);
	printf("PRINTF:\nu int: |%#.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#.X|\n", 0);
	printf("PRINTF:\nu int: |%#-10.15X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.15X|\n", 0);
	printf("PRINTF:\nu int: |%#-10X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10X|\n", 0);
	printf("PRINTF:\nu int: |%#-10.1X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.1X|\n", 0);
	printf("PRINTF:\nu int: |%#-5X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-5X|\n", 0);
	printf("PRINTF:\nu int: |%#10X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10X|\n", 0);
	printf("PRINTF:\nu int: |%#10.15X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.15X|\n", 0);
	printf("PRINTF:\nu int: |%#10.X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.X|\n", 0);
	printf("PRINTF:\nu int: |%#10.1X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.1X|\n", 0);
	printf("PRINTF:\nu int: |%#5X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#5X|\n", 0);
	printf("PRINTF:\nu int: |%#010X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010X|\n", 0);
	printf("PRINTF:\nu int: |%#010.20X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010.20X|\n", 0);
	printf("PRINTF:\nu int: |%#0X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#0X|\n", 0);
	printf("PRINTF:\nu int: |%#04X|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#04X|\n", 0);
	printf("\nBREAK\n");
	printf("PRINTF:\nu int: |%#10llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llX|\n", h);
	printf("PRINTF:\nu int: |%#010llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#010llX|\n", h);
	printf("PRINTF:\nu int: |%#-10llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10llX|\n", h);
	printf("PRINTF:\nu int: |%#-10.15llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.15llX|\n", h);
	printf("PRINTF:\nu int: |%#-10.llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.llX|\n", h);
	printf("PRINTF:\nu int: |%#-10.1llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.1llX|\n", h);
	printf("PRINTF:\nu int: |%#10.1llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.1llX|\n", h);
	printf("PRINTF:\nu int: |%#-10.30llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.30llX|\n", h);
	printf("PRINTF:\nu int: |%#10.30llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.30llX|\n", h);
	printf("PRINTF:\nu int: |%#-5llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-5llX|\n", h);
	printf("PRINTF:\nu int: |%#10llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llX|\n", h);
	printf("PRINTF:\nu int: |%#10.15llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.15llX|\n", h);
	printf("PRINTF:\nu int: |%#10.llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.llX|\n", h);
	printf("PRINTF:\nu int: |%#10.1llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.1llX|\n", h);
	printf("PRINTF:\nu int: |%#5llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#5llX|\n", h);
	printf("PRINTF:\nu int: |%#030llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#030llX|\n", h);
	printf("PRINTF:\nu int: |%#010.20llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.20llX|\n", h);
	printf("PRINTF:\nu int: |%#0llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#0llX|\n", h);
	printf("PRINTF:\nu int: |%#10llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llX|\n", h);
	printf("PRINTF:\nu int: |%#030llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#030llX|\n", h);
	printf("PRINTF:\nu int: |%#030llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#030llX|\n", h);
	printf("PRINTF:\nu int: |%#.llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#.llX|\n", h);
	printf("PRINTF:\nu int: |%#.30llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#.30llX|\n", h);
	printf("PRINTF:\nu int: |%#-.30llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-.30llX|\n", h);
	printf("PRINTF:\nu int: |%#050llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#050llX|\n", h);
	printf("PRINTF:\nu int: |%#llX|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#llX|\n", h); /* only width doesnt work */

	printf("\nUnsigned Small Hexs\n");
	printf("PRINTF:\nu int: |%#10.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.x|\n", 0);
	printf("PRINTF:\nu int: |%#-10.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.x|\n", 0);
	printf("PRINTF:\nu int: |%#010.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010.x|\n", 0);
	printf("PRINTF:\nu int: |%#.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#.x|\n", 0);
	printf("PRINTF:\nu int: |%#-10.15x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.15x|\n", 0);
	printf("PRINTF:\nu int: |%#-10x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10x|\n", 0);
	printf("PRINTF:\nu int: |%#-10.1x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.1x|\n", 0);
	printf("PRINTF:\nu int: |%#-5x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-5x|\n", 0);
	printf("PRINTF:\nu int: |%#10x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10x|\n", 0);
	printf("PRINTF:\nu int: |%#10.15x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.15x|\n", 0);
	printf("PRINTF:\nu int: |%#10.x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.x|\n", 0);
	printf("PRINTF:\nu int: |%#10.1x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.1x|\n", 0);
	printf("PRINTF:\nu int: |%#5x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#5x|\n", 0);
	printf("PRINTF:\nu int: |%#010x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010x|\n", 0);
	printf("PRINTF:\nu int: |%#010.20x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010.20x|\n", 0);
	printf("PRINTF:\nu int: |%#0x|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#0x|\n", 0);
	printf("PRINTF:\nu int: |%#10llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llx|\n", h);
	printf("PRINTF:\nu int: |%#010llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#010llx|\n", h);
	printf("PRINTF:\nu int: |%#-10llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10llx|\n", h);
	printf("PRINTF:\nu int: |%#-10.15llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.15llx|\n", h);
	printf("PRINTF:\nu int: |%#-10.llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.llx|\n", h);
	printf("PRINTF:\nu int: |%#-10.1llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.1llx|\n", h);
	printf("PRINTF:\nu int: |%#10.1llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.1llx|\n", h);
	printf("PRINTF:\nu int: |%#-10.30llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.30llx|\n", h);
	printf("PRINTF:\nu int: |%#10.30llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.30llx|\n", h);
	printf("PRINTF:\nu int: |%#-5llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-5llx|\n", h);
	printf("PRINTF:\nu int: |%#10llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llx|\n", h);
	printf("PRINTF:\nu int: |%#10.15llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.15llx|\n", h);
	printf("PRINTF:\nu int: |%#10.llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.llx|\n", h);
	printf("PRINTF:\nu int: |%#10.1llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.1llx|\n", h);
	printf("PRINTF:\nu int: |%#5llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#5llx|\n", h);
	printf("PRINTF:\nu int: |%#010.20llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.20llx|\n", h);
	printf("PRINTF:\nu int: |%#0llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#0llx|\n", h);
	printf("PRINTF:\nu int: |%#10llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llx|\n", h);
	printf("PRINTF:\nu int: |%#030llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#030llx|----\n", h);/***/
	printf("PRINTF:\nu int: |%#.llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#.llx|\n", h);
	printf("PRINTF:\nu int: |%#.30llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#.30llx|\n", h);
	printf("PRINTF:\nu int: |%#-.30llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-.30llx|\n", h);
	printf("PRINTF:\nu int: |%#050llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#050llx|----\n", h); /**/
	printf("PRINTF:\nu int: |%#050.25llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#050.25llx|\n", h);
	printf("PRINTF:\nu int: |%#50.25llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#50.25llx|\n", h);
	printf("PRINTF:\nu int: |%#50llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#50llx|\n", h);
	printf("PRINTF:\nu int: |%#-050llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-050llx|\n", h);
	printf("PRINTF:\nu int: |%#-50llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-50llx|\n", h);
	printf("PRINTF:\nu int: |%#50llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#50llx|\n", h);
	printf("PRINTF:\nu int: |%#llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#llx|\n", h);


	printf("\nUnsigned Octals:\n");

	printf("PRINTF:\nu int: |%#10.o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.o|\n", 0);
	printf("PRINTF:\nu int: |%#-10.o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.o|\n", 0);
	printf("PRINTF:\nu int: |%#010.o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010.o|\n", 0);
	printf("PRINTF:\nu int: |%#.o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#.o|\n", 0);
	printf("PRINTF:\nu int: |%#-10.15o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.15o|\n", 0);
	printf("PRINTF:\nu int: |%#-10o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10o|\n", 0);
	printf("PRINTF:\nu int: |%#-10.1o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-10.1o|\n", 0);
	printf("PRINTF:\nu int: |%#-5o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#-5o|\n", 0);
	printf("PRINTF:\nu int: |%#10o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10o|\n", 0);
	printf("PRINTF:\nu int: |%#10.15o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.15o|\n", 0);
	printf("PRINTF:\nu int: |%#10.o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.o|\n", 0);
	printf("PRINTF:\nu int: |%#10.1o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#10.1o|\n", 0);
	printf("PRINTF:\nu int: |%#5o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#5o|\n", 0);
	printf("PRINTF:\nu int: |%#010o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010o|\n", 0);
	printf("PRINTF:\nu int: |%#010.20o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#010.20o|\n", 0);
	printf("PRINTF:\nu int: |%#0o|\n", 0);
	ft_printf("MY PRINTF:\nu int: |%#0o|\n", 0);
	printf("PRINTF:\nu int: |%#10.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#10.o|\n", 1);
	printf("PRINTF:\nu int: |%#-10.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#-10.o|\n", 1);
	printf("PRINTF:\nu int: |%#010.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#010.o|\n", 1); /************************/
	printf("PRINTF:\nu int: |%#.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#.o|\n", 1);
	printf("PRINTF:\nu int: |%#-10.15o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#-10.15o|\n", 1);
	printf("PRINTF:\nu int: |%#-10o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#-10o|\n", 1);
	printf("PRINTF:\nu int: |%#-10.1o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#-10.1o|\n", 1);
	printf("PRINTF:\nu int: |%#-5o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#-5o|\n", 1);
	printf("PRINTF:\nu int: |%#10o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#10o|\n", 1);

	printf("\n\n\n\n\n\n\n");
	printf("PRINTF:\nu int: |%#10.15o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#10.15o|\n", 1);
	printf("PRINTF:\nu int: |%#010.15o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#010.15o|\n", 1);
	printf("PRINTF:\nu int: |%#10.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#10.o|\n", 1);
	printf("PRINTF:\nu int: |%#010.o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#010.o|\n", 1);
	printf("PRINTF:\nu int: |%#10.1o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#10.1o|\n", 1);
	printf("PRINTF:\nu int: |%#5o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#5o|\n", 1);
	printf("PRINTF:\nu int: |%#010o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#010o|\n", 1);
	printf("\n\n\n\n\n\n\n");
	printf("PRINTF:\nu int: |%#0.3o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#0.3o|\n", 1);
	printf("PRINTF:\nu int: |%#030.3o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#030.3o|\n", 1);
	printf("PRINTF:\nu int: |%#.3o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#.3o|\n", 1);
	printf("PRINTF:\nu int: |%#10.20o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#10.20o|\n", 1);
	printf("PRINTF:\nu int: |%#010.20o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#010.20o|\n", 1);/************************/
	printf("PRINTF:\nu int: |%#-010.30o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#-010.30o|\n", 1);
	printf("PRINTF:\nu int: |%#010o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#010o|\n", 1);
	printf("PRINTF:\nu int: |%#0o|\n", 1);
	ft_printf("MY PRINTF:\nu int: |%#0o|\n", 1);
	printf("PRINTF:\nu int: |%#10llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llo|\n", h);
	printf("PRINTF:\nu int: |%#010llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#010llo|\n", h);
	printf("PRINTF:\nu int: |%#-10llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10llo|\n", h);
	printf("PRINTF:\nu int: |%#-10.15llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.15llo|\n", h);
	printf("PRINTF:\nu int: |%#-10.llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.llo|\n", h);
	printf("PRINTF:\nu int: |%#-10.1llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.1llo|\n", h);
	printf("PRINTF:\nu int: |%#10.1llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.1llo|\n", h);
	printf("PRINTF:\nu int: |%#-10.30llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-10.30llo|\n", h);
	printf("PRINTF:\nu int: |%#10.30llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.30llo|\n", h);
	printf("PRINTF:\nu int: |%#-5llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-5llo|\n", h);
	printf("PRINTF:\nu int: |%#10llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llo|\n", h);
	printf("PRINTF:\nu int: |%#10.15llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.15llo|\n", h);
	printf("PRINTF:\nu int: |%#10.llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.llo|\n", h);
	printf("PRINTF:\nu int: |%#10.1llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.1llo|\n", h);
	printf("PRINTF:\nu int: |%#5llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#5llo|\n", h);
	printf("PRINTF:\nu int: |%#030llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#030llo|\n", h);
	printf("PRINTF:\nu int: |%#010.20llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10.20llo|\n", h);
	printf("PRINTF:\nu int: |%#0llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#0llo|\n", h);
	printf("PRINTF:\nu int: |%#10llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#10llo|\n", h);
	printf("PRINTF:\nu int: |%#030llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#030llo|\n", h);
	printf("PRINTF:\nu int: |%#030llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#030llo|\n", h);
	printf("PRINTF:\nu int: |%#.llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#.llo|\n", h);
	printf("PRINTF:\nu int: |%#.30llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#.30llo|\n", h);
	printf("PRINTF:\nu int: |%#-.30llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#-.30llo|\n", h);
	printf("PRINTF:\nu int: |%#050llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#050llo|\n", h);
	printf("PRINTF:\nu int: |%#llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#llo|\n", h);
	printf("PRINTF:\nu int: |%#.llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#.llo|\n", h);
	printf("PRINTF:\nu int: |%#.1llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#.1llo|\n", h);
	printf("PRINTF:\nu int: |%#5.25llo|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#5.25llo|\n", h);

	printf("\n\n\n\n\n\n");
	printf("PRINTF:\nu int: |%020llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%020llx|\n", h);
	printf("PRINTF:\nu int: |%#019llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#019llx|\n", h);
	printf("PRINTF:\nu int: |%#018llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#018llx|\n", h);
	printf("PRINTF:\nu int: |%#017llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#017llx|\n----", h);
	printf("PRINTF:\nu int: |%#016llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#016llx|\n", h);
	printf("PRINTF:\nu int: |%#016llx|\n", h);
	ft_printf("MY PRINTF:\nu int: |%#016llx|\n", h);

	re = printf("THE_PRINTF:\nu int: |%#020llx|\n", h);
	my = ft_printf("MY__PRINTF:\nu int: |%#020llx|\n", h);

	printf("\n\nprintf: %i", re);
	printf("\n\nmy: %i\n", my);

	system ("leaks basic");
	return 0;
}

/*n = printf("MY PRINTF:\nu int: |%.llo|\n\t", 0ll);
	printf("\n|%i|", n);
	ft_printf("MY PRINTF:\nu int: |%.llo|\n\t", 0ll);*/

